/** PHB2024 pp178–185. Factual background choices; no narrative copied.
 * https://5e.tools/backgrounds.html (XPHB); official open confirmations:
 * https://www.dndbeyond.com/sources/dnd/br-2024/character-origins
 * Checked2026-10-08. All sixteen PHB2024 backgrounds.
 */
export const backgroundFacts = [
	{
		id: "acolyte",
		name: "Acolyte",
		page: 178,
		abilityChoices: ["intelligence", "wisdom", "charisma"],
		feat: "magic-initiate",
		spellList: "cleric",
		skills: ["insight", "religion"],
		tool: "calligrapher-s-supplies",
	},
	{
		id: "artisan",
		name: "Artisan",
		page: 179,
		abilityChoices: ["strength", "dexterity", "intelligence"],
		feat: "crafter",
		skills: ["investigation", "persuasion"],
		tool: "anyArtisansTool",
	},
	{
		id: "charlatan",
		name: "Charlatan",
		page: 180,
		abilityChoices: ["dexterity", "constitution", "charisma"],
		feat: "skilled",
		skills: ["deception", "sleight-of-hand"],
		tool: "forgery-kit",
	},
	{
		id: "criminal",
		name: "Criminal",
		page: 180,
		abilityChoices: ["dexterity", "constitution", "intelligence"],
		feat: "alert",
		skills: ["sleight-of-hand", "stealth"],
		tool: "thieves-tools",
	},
	{
		id: "entertainer",
		name: "Entertainer",
		page: 180,
		abilityChoices: ["strength", "dexterity", "charisma"],
		feat: "musician",
		skills: ["acrobatics", "performance"],
		tool: "anyMusicalInstrument",
	},
	{
		id: "farmer",
		name: "Farmer",
		page: 180,
		abilityChoices: ["strength", "constitution", "wisdom"],
		feat: "tough",
		skills: ["animal-handling", "nature"],
		tool: "carpenter-s-tools",
	},
	{
		id: "guard",
		name: "Guard",
		page: 181,
		abilityChoices: ["strength", "intelligence", "wisdom"],
		feat: "alert",
		skills: ["athletics", "perception"],
		tool: "anyGamingSet",
	},
	{
		id: "guide",
		name: "Guide",
		page: 181,
		abilityChoices: ["dexterity", "constitution", "wisdom"],
		feat: "magic-initiate",
		spellList: "druid",
		skills: ["stealth", "survival"],
		tool: "cartographer-s-tools",
	},
	{
		id: "hermit",
		name: "Hermit",
		page: 182,
		abilityChoices: ["constitution", "wisdom", "charisma"],
		feat: "healer",
		skills: ["medicine", "religion"],
		tool: "herbalism-kit",
	},
	{
		id: "merchant",
		name: "Merchant",
		page: 182,
		abilityChoices: ["constitution", "intelligence", "charisma"],
		feat: "lucky",
		skills: ["animal-handling", "persuasion"],
		tool: "navigator-s-tools",
	},
	{
		id: "noble",
		name: "Noble",
		page: 183,
		abilityChoices: ["strength", "intelligence", "charisma"],
		feat: "skilled",
		skills: ["history", "persuasion"],
		tool: "anyGamingSet",
	},
	{
		id: "sage",
		name: "Sage",
		page: 183,
		abilityChoices: ["constitution", "intelligence", "wisdom"],
		feat: "magic-initiate",
		spellList: "wizard",
		skills: ["arcana", "history"],
		tool: "calligrapher-s-supplies",
	},
	{
		id: "sailor",
		name: "Sailor",
		page: 184,
		abilityChoices: ["strength", "dexterity", "wisdom"],
		feat: "tavern-brawler",
		skills: ["acrobatics", "perception"],
		tool: "navigator-s-tools",
	},
	{
		id: "scribe",
		name: "Scribe",
		page: 184,
		abilityChoices: ["dexterity", "intelligence", "wisdom"],
		feat: "skilled",
		skills: ["investigation", "perception"],
		tool: "calligrapher-s-supplies",
	},
	{
		id: "soldier",
		name: "Soldier",
		page: 185,
		abilityChoices: ["strength", "dexterity", "constitution"],
		feat: "savage-attacker",
		skills: ["athletics", "intimidation"],
		tool: "anyGamingSet",
	},
	{
		id: "wayfarer",
		name: "Wayfarer",
		page: 185,
		abilityChoices: ["dexterity", "wisdom", "charisma"],
		feat: "lucky",
		skills: ["insight", "stealth"],
		tool: "thieves-tools",
	},
] as const;
export type BackgroundId = (typeof backgroundFacts)[number]["id"];
