/** PHB 2024 chapter5, pp200–211; factual index only (75 feats).
 * Secondary: https://5e.tools/feats.html and https://5e.tools/data/feats.json (XPHB).
 * Official confirmation when open: https://www.dndbeyond.com/sources/dnd/br-2024/feats
 * Checked 2026-10-08; SRD5.2.1 / PHB errata2.0. No source descriptions copied.
 * Blessed Warrior / Druidic Warrior are class alternatives, not chapter5 feats.
 */
export const featCatalogFacts = [
	{
		id: "ability-score-improvement",
		name: "Ability Score Improvement",
		page: 202,
		category: "general",
		repeatable: true,
		level: 4,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 2,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "actor",
		name: "Actor",
		page: 202,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["charisma"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "charisma",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["impersonation", "mimicry"],
	},
	{
		id: "alert",
		name: "Alert",
		page: 200,
		category: "origin",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["initiative-proficiency", "initiative-swap"],
	},
	{
		id: "archery",
		name: "Archery",
		page: 209,
		category: "fighting-style",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "fighting-style",
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "athlete",
		name: "Athlete",
		page: 202,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "strength",
				min: 13,
			},
			{
				ability: "dexterity",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["climb-speed", "hop-up", "jumping"],
	},
	{
		id: "blind-fighting",
		name: "Blind Fighting",
		page: 209,
		category: "fighting-style",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "fighting-style",
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "boon-of-combat-prowess",
		name: "Boon of Combat Prowess",
		page: 210,
		category: "epic-boon",
		repeatable: false,
		level: 19,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 30,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["peerless-aim"],
	},
	{
		id: "boon-of-dimensional-travel",
		name: "Boon of Dimensional Travel",
		page: 210,
		category: "epic-boon",
		repeatable: false,
		level: 19,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 30,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["blink-steps"],
	},
	{
		id: "boon-of-energy-resistance",
		name: "Boon of Energy Resistance",
		page: 210,
		category: "epic-boon",
		repeatable: false,
		level: 19,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 30,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["energy-resistances", "energy-redirection"],
	},
	{
		id: "boon-of-fate",
		name: "Boon of Fate",
		page: 210,
		category: "epic-boon",
		repeatable: false,
		level: 19,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 30,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["improve-fate"],
	},
	{
		id: "boon-of-fortitude",
		name: "Boon of Fortitude",
		page: 210,
		category: "epic-boon",
		repeatable: false,
		level: 19,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 30,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["fortified-health"],
	},
	{
		id: "boon-of-irresistible-offense",
		name: "Boon of Irresistible Offense",
		page: 211,
		category: "epic-boon",
		repeatable: false,
		level: 19,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 30,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["overcome-defenses", "overwhelming-strike"],
	},
	{
		id: "boon-of-recovery",
		name: "Boon of Recovery",
		page: 211,
		category: "epic-boon",
		repeatable: false,
		level: 19,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 30,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["last-stand", "recover-vitality"],
	},
	{
		id: "boon-of-skill",
		name: "Boon of Skill",
		page: 211,
		category: "epic-boon",
		repeatable: false,
		level: 19,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 30,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["all-around-adept", "expertise"],
	},
	{
		id: "boon-of-speed",
		name: "Boon of Speed",
		page: 211,
		category: "epic-boon",
		repeatable: false,
		level: 19,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 30,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["escape-artist", "quickness"],
	},
	{
		id: "boon-of-spell-recall",
		name: "Boon of Spell Recall",
		page: 211,
		category: "epic-boon",
		repeatable: false,
		level: 19,
		abilityChoices: ["intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 30,
		abilityPrerequisites: [],
		requiredFeature: "spellcasting",
		armorPrerequisite: null,
		benefits: ["free-casting"],
	},
	{
		id: "boon-of-the-night-spirit",
		name: "Boon of the Night Spirit",
		page: 211,
		category: "epic-boon",
		repeatable: false,
		level: 19,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 30,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["merge-with-shadows", "shadowy-form"],
	},
	{
		id: "boon-of-truesight",
		name: "Boon of Truesight",
		page: 211,
		category: "epic-boon",
		repeatable: false,
		level: 19,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 30,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["truesight"],
	},
	{
		id: "charger",
		name: "Charger",
		page: 202,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "strength",
				min: 13,
			},
			{
				ability: "dexterity",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["improved-dash", "charge-attack"],
	},
	{
		id: "chef",
		name: "Chef",
		page: 202,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["constitution", "wisdom"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["cook-s-utensils", "replenishing-meal", "bolstering-treats"],
	},
	{
		id: "crafter",
		name: "Crafter",
		page: 200,
		category: "origin",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["tool-proficiency", "discount", "fast-crafting"],
	},
	{
		id: "crossbow-expert",
		name: "Crossbow Expert",
		page: 203,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "dexterity",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["ignore-loading", "firing-in-melee", "dual-wielding"],
	},
	{
		id: "crusher",
		name: "Crusher",
		page: 203,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "constitution"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["push", "enhanced-critical"],
	},
	{
		id: "defense",
		name: "Defense",
		page: 209,
		category: "fighting-style",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "fighting-style",
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "defensive-duelist",
		name: "Defensive Duelist",
		page: 203,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "dexterity",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["parry"],
	},
	{
		id: "dual-wielder",
		name: "Dual Wielder",
		page: 203,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "strength",
				min: 13,
			},
			{
				ability: "dexterity",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["enhanced-dual-wielding", "quick-draw"],
	},
	{
		id: "dueling",
		name: "Dueling",
		page: 209,
		category: "fighting-style",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "fighting-style",
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "durable",
		name: "Durable",
		page: 203,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["constitution"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["defy-death", "speedy-recovery"],
	},
	{
		id: "elemental-adept",
		name: "Elemental Adept",
		page: 203,
		category: "general",
		repeatable: true,
		level: 4,
		abilityChoices: ["intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "spellcasting-or-pact-magic",
		armorPrerequisite: null,
		benefits: ["energy-mastery"],
	},
	{
		id: "fey-touched",
		name: "Fey-Touched",
		page: 204,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["fey-magic"],
	},
	{
		id: "grappler",
		name: "Grappler",
		page: 204,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "strength",
				min: 13,
			},
			{
				ability: "dexterity",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["punch-and-grab", "attack-advantage", "fast-wrestler"],
	},
	{
		id: "great-weapon-fighting",
		name: "Great Weapon Fighting",
		page: 209,
		category: "fighting-style",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "fighting-style",
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "great-weapon-master",
		name: "Great Weapon Master",
		page: 204,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "strength",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["heavy-weapon-mastery", "hew"],
	},
	{
		id: "healer",
		name: "Healer",
		page: 201,
		category: "origin",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["battle-medic", "healing-rerolls"],
	},
	{
		id: "heavily-armored",
		name: "Heavily Armored",
		page: 204,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["constitution", "strength"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: "medium",
		benefits: ["armor-training"],
	},
	{
		id: "heavy-armor-master",
		name: "Heavy Armor Master",
		page: 204,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["constitution", "strength"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: "heavy",
		benefits: ["damage-reduction"],
	},
	{
		id: "inspiring-leader",
		name: "Inspiring Leader",
		page: 204,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["wisdom", "charisma"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "wisdom",
				min: 13,
			},
			{
				ability: "charisma",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["bolstering-performance"],
	},
	{
		id: "interception",
		name: "Interception",
		page: 209,
		category: "fighting-style",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "fighting-style",
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "keen-mind",
		name: "Keen Mind",
		page: 205,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["intelligence"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "intelligence",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["lore-knowledge", "quick-study"],
	},
	{
		id: "lightly-armored",
		name: "Lightly Armored",
		page: 205,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["armor-training"],
	},
	{
		id: "lucky",
		name: "Lucky",
		page: 201,
		category: "origin",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["luck-points", "advantage", "disadvantage"],
	},
	{
		id: "mage-slayer",
		name: "Mage Slayer",
		page: 205,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["concentration-breaker", "guarded-mind"],
	},
	{
		id: "magic-initiate",
		name: "Magic Initiate",
		page: 201,
		category: "origin",
		repeatable: true,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["two-cantrips", "level-1-spell", "spell-change"],
	},
	{
		id: "martial-weapon-training",
		name: "Martial Weapon Training",
		page: 205,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["weapon-proficiency"],
	},
	{
		id: "medium-armor-master",
		name: "Medium Armor Master",
		page: 205,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: "medium",
		benefits: ["dexterous-wearer"],
	},
	{
		id: "moderately-armored",
		name: "Moderately Armored",
		page: 205,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: "light",
		benefits: ["armor-training"],
	},
	{
		id: "mounted-combatant",
		name: "Mounted Combatant",
		page: 205,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity", "wisdom"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["mounted-strike", "leap-aside", "veer"],
	},
	{
		id: "musician",
		name: "Musician",
		page: 201,
		category: "origin",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["instrument-training", "encouraging-song"],
	},
	{
		id: "observant",
		name: "Observant",
		page: 205,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["intelligence", "wisdom"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "intelligence",
				min: 13,
			},
			{
				ability: "wisdom",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["keen-observer", "quick-search"],
	},
	{
		id: "piercer",
		name: "Piercer",
		page: 206,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["puncture", "enhanced-critical"],
	},
	{
		id: "poisoner",
		name: "Poisoner",
		page: 206,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["dexterity", "intelligence"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["potent-poison", "brew-poison"],
	},
	{
		id: "polearm-master",
		name: "Polearm Master",
		page: 206,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["dexterity", "strength"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "strength",
				min: 13,
			},
			{
				ability: "dexterity",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["pole-strike", "reactive-strike"],
	},
	{
		id: "protection",
		name: "Protection",
		page: 209,
		category: "fighting-style",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "fighting-style",
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "resilient",
		name: "Resilient",
		page: 206,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["saving-throw-proficiency"],
	},
	{
		id: "ritual-caster",
		name: "Ritual Caster",
		page: 206,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "intelligence",
				min: 13,
			},
			{
				ability: "wisdom",
				min: 13,
			},
			{
				ability: "charisma",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["ritual-spells", "quick-ritual"],
	},
	{
		id: "savage-attacker",
		name: "Savage Attacker",
		page: 201,
		category: "origin",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "sentinel",
		name: "Sentinel",
		page: 207,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "strength",
				min: 13,
			},
			{
				ability: "dexterity",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["guardian", "halt"],
	},
	{
		id: "shadow-touched",
		name: "Shadow-Touched",
		page: 207,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["shadow-magic"],
	},
	{
		id: "sharpshooter",
		name: "Sharpshooter",
		page: 207,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "dexterity",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["bypass-cover", "firing-in-melee", "long-shots"],
	},
	{
		id: "shield-master",
		name: "Shield Master",
		page: 207,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: "shield",
		benefits: ["shield-bash", "interpose-shield"],
	},
	{
		id: "skill-expert",
		name: "Skill Expert",
		page: 207,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["skill-proficiency", "expertise"],
	},
	{
		id: "skilled",
		name: "Skilled",
		page: 201,
		category: "origin",
		repeatable: true,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "skulker",
		name: "Skulker",
		page: 208,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "dexterity",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["blindsight", "fog-of-war", "sniper"],
	},
	{
		id: "slasher",
		name: "Slasher",
		page: 208,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["hamstring", "enhanced-critical"],
	},
	{
		id: "speedy",
		name: "Speedy",
		page: 208,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["dexterity", "constitution"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [
			{
				ability: "dexterity",
				min: 13,
			},
			{
				ability: "constitution",
				min: 13,
			},
		],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["speed-increase", "dash-over-difficult-terrain", "agile-movement"],
	},
	{
		id: "spell-sniper",
		name: "Spell Sniper",
		page: 208,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "spellcasting-or-pact-magic",
		armorPrerequisite: null,
		benefits: ["bypass-cover", "casting-in-melee", "increased-range"],
	},
	{
		id: "tavern-brawler",
		name: "Tavern Brawler",
		page: 202,
		category: "origin",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["enhanced-unarmed-strike", "damage-rerolls", "improvised-weaponry", "push"],
	},
	{
		id: "telekinetic",
		name: "Telekinetic",
		page: 208,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["minor-telekinesis", "telekinetic-shove"],
	},
	{
		id: "telepathic",
		name: "Telepathic",
		page: 208,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["telepathic-utterance", "detect-thoughts"],
	},
	{
		id: "thrown-weapon-fighting",
		name: "Thrown Weapon Fighting",
		page: 210,
		category: "fighting-style",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "fighting-style",
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "tough",
		name: "Tough",
		page: 202,
		category: "origin",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "two-weapon-fighting",
		name: "Two-Weapon Fighting",
		page: 210,
		category: "fighting-style",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "fighting-style",
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "unarmed-fighting",
		name: "Unarmed Fighting",
		page: 210,
		category: "fighting-style",
		repeatable: false,
		level: 1,
		abilityChoices: [],
		abilityPoints: 0,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "fighting-style",
		armorPrerequisite: null,
		benefits: [],
	},
	{
		id: "war-caster",
		name: "War Caster",
		page: 209,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["intelligence", "wisdom", "charisma"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: "spellcasting-or-pact-magic",
		armorPrerequisite: null,
		benefits: ["concentration", "reactive-spell", "somatic-components"],
	},
	{
		id: "weapon-master",
		name: "Weapon Master",
		page: 209,
		category: "general",
		repeatable: false,
		level: 4,
		abilityChoices: ["strength", "dexterity"],
		abilityPoints: 1,
		cap: 20,
		abilityPrerequisites: [],
		requiredFeature: null,
		armorPrerequisite: null,
		benefits: ["mastery-property"],
	},
] as const;
export type FeatCatalogId = (typeof featCatalogFacts)[number]["id"];
