/** Selection validation only; no spell resolution or copyrighted descriptions.
 * PHB2024 level0/1 spell metadata / https://5e.tools/spells.html (XPHB).
 * Checked2026-10-08. Required for MagicInitiate/FeyTouched/ShadowTouched/RitualCaster legality.
 */
export const spellChoiceIndex = [
	{
		id: "acid-splash",
		name: "Acid Splash",
		level: 0,
		school: "V",
		ritual: false,
		lists: ["sorcerer", "wizard"],
	},
	{
		id: "alarm",
		name: "Alarm",
		level: 1,
		school: "A",
		ritual: true,
		lists: ["ranger", "wizard"],
	},
	{
		id: "animal-friendship",
		name: "Animal Friendship",
		level: 1,
		school: "E",
		ritual: false,
		lists: ["bard", "druid", "ranger"],
	},
	{
		id: "armor-of-agathys",
		name: "Armor of Agathys",
		level: 1,
		school: "A",
		ritual: false,
		lists: ["warlock"],
	},
	{
		id: "arms-of-hadar",
		name: "Arms of Hadar",
		level: 1,
		school: "C",
		ritual: false,
		lists: ["warlock"],
	},
	{
		id: "bane",
		name: "Bane",
		level: 1,
		school: "E",
		ritual: false,
		lists: ["bard", "cleric", "warlock"],
	},
	{
		id: "blade-ward",
		name: "Blade Ward",
		level: 0,
		school: "A",
		ritual: false,
		lists: ["bard", "sorcerer", "warlock", "wizard"],
	},
	{
		id: "bless",
		name: "Bless",
		level: 1,
		school: "E",
		ritual: false,
		lists: ["cleric", "paladin"],
	},
	{
		id: "burning-hands",
		name: "Burning Hands",
		level: 1,
		school: "V",
		ritual: false,
		lists: ["sorcerer", "wizard"],
	},
	{
		id: "charm-person",
		name: "Charm Person",
		level: 1,
		school: "E",
		ritual: false,
		lists: ["bard", "druid", "sorcerer", "warlock", "wizard"],
	},
	{
		id: "chill-touch",
		name: "Chill Touch",
		level: 0,
		school: "N",
		ritual: false,
		lists: ["sorcerer", "warlock", "wizard"],
	},
	{
		id: "chromatic-orb",
		name: "Chromatic Orb",
		level: 1,
		school: "V",
		ritual: false,
		lists: ["sorcerer", "wizard"],
	},
	{
		id: "color-spray",
		name: "Color Spray",
		level: 1,
		school: "I",
		ritual: false,
		lists: ["bard", "sorcerer", "wizard"],
	},
	{
		id: "command",
		name: "Command",
		level: 1,
		school: "E",
		ritual: false,
		lists: ["bard", "cleric", "paladin"],
	},
	{
		id: "compelled-duel",
		name: "Compelled Duel",
		level: 1,
		school: "E",
		ritual: false,
		lists: ["paladin"],
	},
	{
		id: "comprehend-languages",
		name: "Comprehend Languages",
		level: 1,
		school: "D",
		ritual: true,
		lists: ["bard", "sorcerer", "warlock", "wizard"],
	},
	{
		id: "create-or-destroy-water",
		name: "Create or Destroy Water",
		level: 1,
		school: "T",
		ritual: false,
		lists: ["cleric", "druid"],
	},
	{
		id: "cure-wounds",
		name: "Cure Wounds",
		level: 1,
		school: "A",
		ritual: false,
		lists: ["bard", "cleric", "druid", "ranger", "paladin"],
	},
	{
		id: "dancing-lights",
		name: "Dancing Lights",
		level: 0,
		school: "I",
		ritual: false,
		lists: ["bard", "sorcerer", "wizard"],
	},
	{
		id: "detect-evil-and-good",
		name: "Detect Evil and Good",
		level: 1,
		school: "D",
		ritual: false,
		lists: ["cleric", "paladin"],
	},
	{
		id: "detect-magic",
		name: "Detect Magic",
		level: 1,
		school: "D",
		ritual: true,
		lists: ["bard", "cleric", "druid", "ranger", "sorcerer", "warlock", "wizard", "paladin"],
	},
	{
		id: "detect-poison-and-disease",
		name: "Detect Poison and Disease",
		level: 1,
		school: "D",
		ritual: true,
		lists: ["cleric", "druid", "ranger", "paladin"],
	},
	{
		id: "disguise-self",
		name: "Disguise Self",
		level: 1,
		school: "I",
		ritual: false,
		lists: ["bard", "sorcerer", "wizard"],
	},
	{
		id: "dissonant-whispers",
		name: "Dissonant Whispers",
		level: 1,
		school: "E",
		ritual: false,
		lists: ["bard"],
	},
	{
		id: "divine-favor",
		name: "Divine Favor",
		level: 1,
		school: "T",
		ritual: false,
		lists: ["paladin"],
	},
	{
		id: "divine-smite",
		name: "Divine Smite",
		level: 1,
		school: "V",
		ritual: false,
		lists: ["paladin"],
	},
	{
		id: "druidcraft",
		name: "Druidcraft",
		level: 0,
		school: "T",
		ritual: false,
		lists: ["druid"],
	},
	{
		id: "eldritch-blast",
		name: "Eldritch Blast",
		level: 0,
		school: "V",
		ritual: false,
		lists: ["warlock"],
	},
	{
		id: "elementalism",
		name: "Elementalism",
		level: 0,
		school: "T",
		ritual: false,
		lists: ["druid", "sorcerer", "wizard"],
	},
	{
		id: "ensnaring-strike",
		name: "Ensnaring Strike",
		level: 1,
		school: "C",
		ritual: false,
		lists: ["ranger"],
	},
	{
		id: "entangle",
		name: "Entangle",
		level: 1,
		school: "C",
		ritual: false,
		lists: ["druid", "ranger"],
	},
	{
		id: "expeditious-retreat",
		name: "Expeditious Retreat",
		level: 1,
		school: "T",
		ritual: false,
		lists: ["sorcerer", "warlock", "wizard"],
	},
	{
		id: "faerie-fire",
		name: "Faerie Fire",
		level: 1,
		school: "V",
		ritual: false,
		lists: ["bard", "druid"],
	},
	{
		id: "false-life",
		name: "False Life",
		level: 1,
		school: "N",
		ritual: false,
		lists: ["sorcerer", "wizard"],
	},
	{
		id: "feather-fall",
		name: "Feather Fall",
		level: 1,
		school: "T",
		ritual: false,
		lists: ["bard", "sorcerer", "wizard"],
	},
	{
		id: "find-familiar",
		name: "Find Familiar",
		level: 1,
		school: "C",
		ritual: true,
		lists: ["wizard"],
	},
	{
		id: "fire-bolt",
		name: "Fire Bolt",
		level: 0,
		school: "V",
		ritual: false,
		lists: ["sorcerer", "wizard"],
	},
	{
		id: "fog-cloud",
		name: "Fog Cloud",
		level: 1,
		school: "C",
		ritual: false,
		lists: ["druid", "ranger", "sorcerer", "wizard"],
	},
	{
		id: "friends",
		name: "Friends",
		level: 0,
		school: "E",
		ritual: false,
		lists: ["bard", "sorcerer", "warlock", "wizard"],
	},
	{
		id: "goodberry",
		name: "Goodberry",
		level: 1,
		school: "C",
		ritual: false,
		lists: ["druid", "ranger"],
	},
	{
		id: "grease",
		name: "Grease",
		level: 1,
		school: "C",
		ritual: false,
		lists: ["sorcerer", "wizard"],
	},
	{
		id: "guidance",
		name: "Guidance",
		level: 0,
		school: "D",
		ritual: false,
		lists: ["cleric", "druid"],
	},
	{
		id: "guiding-bolt",
		name: "Guiding Bolt",
		level: 1,
		school: "V",
		ritual: false,
		lists: ["cleric"],
	},
	{
		id: "hail-of-thorns",
		name: "Hail of Thorns",
		level: 1,
		school: "C",
		ritual: false,
		lists: ["ranger"],
	},
	{
		id: "healing-word",
		name: "Healing Word",
		level: 1,
		school: "A",
		ritual: false,
		lists: ["bard", "cleric", "druid"],
	},
	{
		id: "hellish-rebuke",
		name: "Hellish Rebuke",
		level: 1,
		school: "V",
		ritual: false,
		lists: ["warlock"],
	},
	{
		id: "heroism",
		name: "Heroism",
		level: 1,
		school: "E",
		ritual: false,
		lists: ["bard", "paladin"],
	},
	{
		id: "hex",
		name: "Hex",
		level: 1,
		school: "E",
		ritual: false,
		lists: ["warlock"],
	},
	{
		id: "hunter-s-mark",
		name: "Hunter's Mark",
		level: 1,
		school: "D",
		ritual: false,
		lists: ["ranger"],
	},
	{
		id: "ice-knife",
		name: "Ice Knife",
		level: 1,
		school: "C",
		ritual: false,
		lists: ["druid", "sorcerer", "wizard"],
	},
	{
		id: "identify",
		name: "Identify",
		level: 1,
		school: "D",
		ritual: true,
		lists: ["bard", "wizard"],
	},
	{
		id: "illusory-script",
		name: "Illusory Script",
		level: 1,
		school: "I",
		ritual: true,
		lists: ["bard", "warlock", "wizard"],
	},
	{
		id: "inflict-wounds",
		name: "Inflict Wounds",
		level: 1,
		school: "N",
		ritual: false,
		lists: ["cleric"],
	},
	{
		id: "jump",
		name: "Jump",
		level: 1,
		school: "T",
		ritual: false,
		lists: ["druid", "ranger", "sorcerer", "wizard"],
	},
	{
		id: "light",
		name: "Light",
		level: 0,
		school: "V",
		ritual: false,
		lists: ["bard", "cleric", "sorcerer", "wizard"],
	},
	{
		id: "longstrider",
		name: "Longstrider",
		level: 1,
		school: "T",
		ritual: false,
		lists: ["bard", "druid", "ranger", "wizard"],
	},
	{
		id: "mage-armor",
		name: "Mage Armor",
		level: 1,
		school: "A",
		ritual: false,
		lists: ["sorcerer", "wizard"],
	},
	{
		id: "mage-hand",
		name: "Mage Hand",
		level: 0,
		school: "C",
		ritual: false,
		lists: ["bard", "sorcerer", "warlock", "wizard"],
	},
	{
		id: "magic-missile",
		name: "Magic Missile",
		level: 1,
		school: "V",
		ritual: false,
		lists: ["sorcerer", "wizard"],
	},
	{
		id: "mending",
		name: "Mending",
		level: 0,
		school: "T",
		ritual: false,
		lists: ["bard", "cleric", "druid", "sorcerer", "wizard"],
	},
	{
		id: "message",
		name: "Message",
		level: 0,
		school: "T",
		ritual: false,
		lists: ["bard", "druid", "sorcerer", "wizard"],
	},
	{
		id: "mind-sliver",
		name: "Mind Sliver",
		level: 0,
		school: "E",
		ritual: false,
		lists: ["sorcerer", "warlock", "wizard"],
	},
	{
		id: "minor-illusion",
		name: "Minor Illusion",
		level: 0,
		school: "I",
		ritual: false,
		lists: ["bard", "sorcerer", "warlock", "wizard"],
	},
	{
		id: "poison-spray",
		name: "Poison Spray",
		level: 0,
		school: "N",
		ritual: false,
		lists: ["druid", "sorcerer", "warlock", "wizard"],
	},
	{
		id: "prestidigitation",
		name: "Prestidigitation",
		level: 0,
		school: "T",
		ritual: false,
		lists: ["bard", "sorcerer", "warlock", "wizard"],
	},
	{
		id: "produce-flame",
		name: "Produce Flame",
		level: 0,
		school: "C",
		ritual: false,
		lists: ["druid"],
	},
	{
		id: "protection-from-evil-and-good",
		name: "Protection from Evil and Good",
		level: 1,
		school: "A",
		ritual: false,
		lists: ["cleric", "druid", "warlock", "wizard", "paladin"],
	},
	{
		id: "purify-food-and-drink",
		name: "Purify Food and Drink",
		level: 1,
		school: "T",
		ritual: true,
		lists: ["cleric", "druid", "paladin"],
	},
	{
		id: "ray-of-frost",
		name: "Ray of Frost",
		level: 0,
		school: "V",
		ritual: false,
		lists: ["sorcerer", "wizard"],
	},
	{
		id: "ray-of-sickness",
		name: "Ray of Sickness",
		level: 1,
		school: "N",
		ritual: false,
		lists: ["sorcerer", "wizard"],
	},
	{
		id: "resistance",
		name: "Resistance",
		level: 0,
		school: "A",
		ritual: false,
		lists: ["cleric", "druid"],
	},
	{
		id: "sacred-flame",
		name: "Sacred Flame",
		level: 0,
		school: "V",
		ritual: false,
		lists: ["cleric"],
	},
	{
		id: "sanctuary",
		name: "Sanctuary",
		level: 1,
		school: "A",
		ritual: false,
		lists: ["cleric"],
	},
	{
		id: "searing-smite",
		name: "Searing Smite",
		level: 1,
		school: "V",
		ritual: false,
		lists: ["paladin"],
	},
	{
		id: "shield",
		name: "Shield",
		level: 1,
		school: "A",
		ritual: false,
		lists: ["sorcerer", "wizard"],
	},
	{
		id: "shield-of-faith",
		name: "Shield of Faith",
		level: 1,
		school: "A",
		ritual: false,
		lists: ["cleric", "paladin"],
	},
	{
		id: "shillelagh",
		name: "Shillelagh",
		level: 0,
		school: "T",
		ritual: false,
		lists: ["druid"],
	},
	{
		id: "shocking-grasp",
		name: "Shocking Grasp",
		level: 0,
		school: "V",
		ritual: false,
		lists: ["sorcerer", "wizard"],
	},
	{
		id: "silent-image",
		name: "Silent Image",
		level: 1,
		school: "I",
		ritual: false,
		lists: ["bard", "sorcerer", "wizard"],
	},
	{
		id: "sleep",
		name: "Sleep",
		level: 1,
		school: "E",
		ritual: false,
		lists: ["bard", "sorcerer", "wizard"],
	},
	{
		id: "sorcerous-burst",
		name: "Sorcerous Burst",
		level: 0,
		school: "V",
		ritual: false,
		lists: ["sorcerer"],
	},
	{
		id: "spare-the-dying",
		name: "Spare the Dying",
		level: 0,
		school: "N",
		ritual: false,
		lists: ["cleric", "druid"],
	},
	{
		id: "speak-with-animals",
		name: "Speak with Animals",
		level: 1,
		school: "D",
		ritual: true,
		lists: ["bard", "druid", "ranger", "warlock"],
	},
	{
		id: "starry-wisp",
		name: "Starry Wisp",
		level: 0,
		school: "V",
		ritual: false,
		lists: ["bard", "druid"],
	},
	{
		id: "tasha-s-hideous-laughter",
		name: "Tasha's Hideous Laughter",
		level: 1,
		school: "E",
		ritual: false,
		lists: ["bard", "warlock", "wizard"],
	},
	{
		id: "tenser-s-floating-disk",
		name: "Tenser's Floating Disk",
		level: 1,
		school: "C",
		ritual: true,
		lists: ["wizard"],
	},
	{
		id: "thaumaturgy",
		name: "Thaumaturgy",
		level: 0,
		school: "T",
		ritual: false,
		lists: ["cleric"],
	},
	{
		id: "thorn-whip",
		name: "Thorn Whip",
		level: 0,
		school: "T",
		ritual: false,
		lists: ["druid"],
	},
	{
		id: "thunderclap",
		name: "Thunderclap",
		level: 0,
		school: "V",
		ritual: false,
		lists: ["bard", "druid", "sorcerer", "warlock", "wizard"],
	},
	{
		id: "thunderous-smite",
		name: "Thunderous Smite",
		level: 1,
		school: "V",
		ritual: false,
		lists: ["paladin"],
	},
	{
		id: "thunderwave",
		name: "Thunderwave",
		level: 1,
		school: "V",
		ritual: false,
		lists: ["bard", "druid", "sorcerer", "wizard"],
	},
	{
		id: "toll-the-dead",
		name: "Toll the Dead",
		level: 0,
		school: "N",
		ritual: false,
		lists: ["cleric", "warlock", "wizard"],
	},
	{
		id: "true-strike",
		name: "True Strike",
		level: 0,
		school: "D",
		ritual: false,
		lists: ["bard", "sorcerer", "warlock", "wizard"],
	},
	{
		id: "unseen-servant",
		name: "Unseen Servant",
		level: 1,
		school: "C",
		ritual: true,
		lists: ["bard", "warlock", "wizard"],
	},
	{
		id: "vicious-mockery",
		name: "Vicious Mockery",
		level: 0,
		school: "E",
		ritual: false,
		lists: ["bard"],
	},
	{
		id: "witch-bolt",
		name: "Witch Bolt",
		level: 1,
		school: "V",
		ritual: false,
		lists: ["sorcerer", "warlock", "wizard"],
	},
	{
		id: "word-of-radiance",
		name: "Word of Radiance",
		level: 0,
		school: "V",
		ritual: false,
		lists: ["cleric"],
	},
	{
		id: "wrathful-smite",
		name: "Wrathful Smite",
		level: 1,
		school: "N",
		ritual: false,
		lists: ["paladin"],
	},
] as const;
